services:
  event-listener:
    container_name: event-listener
    build: ../cont/event-listener
    environment:
      HOST_GID: ${HOST_UID}
      HOST_UID: ${HOST_UID}
      HTTP_PORT: ${HTTP_PORT}
      TZ: ${TIME_ZONE}
      AUTORELOAD_PROGRAMS: "swoole"
      AUTORELOAD_ANY_FILES: 1
    expose: 
    - ${HTTP_PORT}
    ports: 
    - ${HTTP_PORT}:${HTTP_PORT}
    volumes:
    - ../../../../dev:/var/www
      